import Footer from "@/components/Footer";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import dynamic from "next/dynamic";
import { Suspense } from "react";
import Loading from "@/components/loading";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// const CrispWithNoSSR = dynamic(() => import("../components/CrispChat"));

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} mx-auto max-w-[1400px] rmd:px-8 rlg:px-12 px-24 bg-custom-blue`}
            >
                <Navbar />

                <section className="mt-12"> {children}</section>

                {/* <CrispWithNoSSR /> */}

                <Footer />
            </body>
        </html>
    );
}
