import Footer from "@/components/Footer";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const CrispWithNoSSR = dynamic(() => import("../components/CrispChat"));

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${inter.className} mx-auto max-w-[1400px] px-12`}>
                <Navbar />

                {children}

                <CrispWithNoSSR />

                <Footer />
            </body>
        </html>
    );
}
